### ISSUE TITLE
Missing support for events?

### ISSUE THREAD

**Issue by asabil** [TylorS167/mostly-dom#15]
I am currently looking at mostly-dom as an improved snabbdom with better typing and less polymorphism. I am wondering if events are/will be supported in mostly-dom similarly to how snabbdom implements them?

**Comment by TylorS** [comment]
It's possible that the current snabbdom events module could be supported by mostly-dom. Ive originally skipped it because in motorcycle events are handled outside of the view code. 

However, I've wanted to make a port, but I definitely want to have the typings be as exhaustive as the current types for properties etc. So for each given element, there should be corresponding event types specific to each element. 

If be very willing to accept a PR for this if you're interested in doing the work, otherwise I can not give a timeline on when I'll get it done myself.


P.S. thanks for your issue and your interest in mostly-dom!

**Comment by TylorS** [comment]
@asabil This is released in v3.4.0, try it out and let use know what you think!

**Comment by asabil** [comment]
Wow, awesome! Thanks. I will try it and report back
